### ISSUE TITLE
Function example is for the wrong function.

### ISSUE THREAD

**Issue by TheSecondQuaid** [tobor88/CybereasonAPI#3]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, necessarily, just missing the proper example for a function in CybereasonAPI.psm1, line 3738. It references the preceding function (Set-CybereasonCustomDetectionRule) rather than the current one being described (Get-CybereasonListAllSensor).

**Describe the solution you'd like**
Should be updated to include an example for the correct function. Perhaps something like:
`Get-CybereasonListAllSensor -Limit 1000 -Offset 0 -Sort DESC -Filter osType:WINDOWS`

**Describe alternatives you've considered**
N/A

**Additional context**
Not functionality-breaking at all, but would be beneficial to anyone who genuinely needs an example to help get them started with the function. I apologize if this was done inccorrectly, as well, as I haven't opened many issues in Github yet :).

**Comment by tobor88** [comment]
Thanks! I have updated that in the git repo
